#!/usr/bin/env python3
"""Re-print a generated sheet's ink onto the shared Seasons paper stock.

The four Seasons covers (28-31) are composed on assets/seasons/paper.jpeg.
The fourteen interior sheets (32-45) are generated by the model, and each one
comes out on its own slightly different paper white point. This tool removes
that difference without touching the artwork:

    1. estimate the sheet's own paper white point Pw (per channel median of the
       pixels above the 85th luminance percentile -- i.e. the blank paper),
    2. divide the sheet by Pw to recover pure ink density  (blank paper -> 1.0,
       solid ink -> near 0), clamped a little above 1.0 so specular paper fibre
       does not blow out,
    3. multiply that density back onto the shared paper stock.

Blank areas land exactly on the cover paper. Ink density and hue survive,
because the operation is a per-channel ratio, not a colour cast.
"""

from __future__ import annotations

import argparse
import pathlib

import numpy as np
from PIL import Image

REPO = pathlib.Path(__file__).resolve().parent.parent
PAPER = REPO / "assets" / "seasons" / "paper.jpeg"
COVER = REPO / "posters" / "img" / "28-seasons-spring.jpeg"

WHITE_PERCENTILE = 85.0   # pixels above this luminance count as blank paper
RATIO_CEILING = 1.00      # blank paper lands exactly on the shared stock
GRAIN_STRENGTH = 0.22     # same value as tools/seasons_compose.py


def white_point(arr: np.ndarray) -> np.ndarray:
    """Per-channel median of the blank-paper pixels."""
    lum = arr.mean(axis=2)
    mask = lum >= np.percentile(lum, WHITE_PERCENTILE)
    return np.array([np.median(arr[..., c][mask]) for c in range(3)], dtype=float)


def target_white() -> np.ndarray:
    """The white point of the four Seasons covers, measured, not guessed."""
    if not COVER.exists():
        return np.array([230.0, 222.0, 204.0])
    return white_point(np.asarray(Image.open(COVER).convert("RGB"), dtype=float))


def load_paper(size: tuple[int, int]) -> np.ndarray:
    stock = Image.open(PAPER).convert("RGB")
    if stock.size != size:
        stock = stock.resize(size, Image.LANCZOS)
    return np.asarray(stock, dtype=float)


def normalize(src: pathlib.Path) -> Image.Image:
    img = Image.open(src).convert("RGB")
    arr = np.asarray(img, dtype=float)

    pw = white_point(arr)
    density = np.clip(arr / np.maximum(pw, 1.0), 0.0, RATIO_CEILING)

    stock = load_paper(img.size)
    out = stock * density

    # Identical final pass to tools/seasons_compose.py: pull the shared paper
    # fibre back over everything, so interior sheets and covers come off the
    # same press with the same white point.
    grain = stock.mean(axis=2) / 255.0
    grain = 1.0 - (1.0 - grain) * GRAIN_STRENGTH
    out *= grain[..., None]

    # Final exact match: land the blank paper on the covers' measured white
    # point, so all eighteen Seasons sheets read as one stock.
    out *= (target_white() / np.maximum(white_point(out), 1.0))

    return Image.fromarray(np.clip(out, 0, 255).astype(np.uint8), "RGB")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("src", nargs="+", type=pathlib.Path)
    ap.add_argument("--outdir", type=pathlib.Path, required=True)
    ap.add_argument("--width", type=int, default=1200, help="archive width, 0 = keep")
    ap.add_argument("--quality", type=int, default=88)
    args = ap.parse_args()

    args.outdir.mkdir(parents=True, exist_ok=True)
    for src in args.src:
        img = normalize(src)
        if args.width and img.width != args.width:
            h = round(img.height * args.width / img.width)
            img = img.resize((args.width, h), Image.LANCZOS)
        dst = args.outdir / (src.stem + ".jpeg")
        img.save(dst, "JPEG", quality=args.quality, optimize=True, progressive=True)
        print(f"{src.name} -> {dst}  {img.width}x{img.height}")


if __name__ == "__main__":
    main()
